### ISSUE TITLE
[Solved] Activating waypoint from target window, gives a wrong longitude value 

### ISSUE THREAD

**Issue by Brusura** [neuoy/KSPTrajectories#136]
The waypoint is created with scansat gui

As reported here:

https://forum.kerbalspaceprogram.com/index.php?/topic/162324-131-trajectories-v200-2018-02-15-atmospheric-predictions/&do=findComment&comment=3316715

VIDEO:
https://youtu.be/VyxhHvIK8Hk

OUTPUT_LOG:
https://drive.google.com/open?id=0B4kd548FeSEpTnRSSWtLVHVsNzA

KSP:
1.3.1 x64 en ( stock cubes )

Trajectories 2.0.0

Mod list ( sorry for the long list ):
AirPark.1.6.2.0_11242017
BetterBurnTime-1.6.1
Community_Resource_Pack-0.8.0.0
CTI.0.1.9
Decoupler_Shroud-0.3.1
DockRotate-1.3.1.5
EasyVesselSwitch_v1.5
EnvironmentalVisualEnhancements-1.2.2.1
IndicatorLights-1.2.12
KAS_v0.6.3
KerbalAlarmClock_3.8.5.0
KerbalEngineer-1.1.3.0
KerbalJointReinforcement_v3.3.3
KIS_v1.9
Malemute_0.4.0.0
ModuleManager.3.0.1.dll
NavBallDockingAlignmentIndicatorCE-1.0.3
Near_Future_Electrical-0.9.8
Near_Future_Solar-0.8.8
OSEWorkshop-1.2.3
ParaSciEVEPack120
Portrait_Stats-15.1
PreciseManeuver
SCANsat-v18.4
SimpleAdjustableFairings-KWRocketry-v1.0.1
SimpleLogistics-2.0.2
Snacks_1_8_7
Stockalike_Station_Parts_Expansion_Redux-1.0.2
Trajectories-v2.0.0
TransferWindowPlanner_1.6.2.0
UbioWeldContinued-2.5.2
USITools_0.10.1.0
VertVel132

**Comment by PiezPiedPy** [comment]
It appears the Target from waypoint longitude is 180 degrees out of position, hopefully a small issue to fix.

**Comment by JebsSY** [comment]
I assume this is, because KSP 1.3.1+ changed the reference frame on CelestialBody.GetRelSurfacePosition.

Since then, the longitude is wrong, when using this function as before. See also:

https://forum.kerbalspaceprogram.com/index.php?/topic/97154-131-throttle-controlled-avionics/&page=69&tab=comments#comment-3216537

Some people changed from:
"Body".GetRelSurfacePosition(Latitude, Longitude, alt + Altitude);
to
"Body".GetWorldSurfacePosition(Latitude, Longitude, alt + Altitude) - "Body".position;

Which seem to be half of a solution. It's spot on on the loading of the szene, but is drifting as time goes by.
But it is still better than using the old version.

**Comment by PiezPiedPy** [comment]
@JebsSY Well spotted 😉 it appears you are correct, looking at the code that sets the Waypoint Target I see that the old method is used but the new method has been used for the Manual Target which works fine.
I'll update the code very soon and get this in for the next release.

**Comment by PiezPiedPy** [comment]
Fixed 😃

**Comment by dlrk2** [comment]
Is the new release for this backwards-compatible?

**Comment by PiezPiedPy** [comment]
@dlrk2 When building a version of Trajectories for a specific version of KSP the Unity versions have to match, since KSPv.4.1 is built with a different version of Unity than was used with KSP v1.3.1 I doubt it will work but you can try.

**Comment by dlrk2** [comment]
2.1 appears to work with 1.3.1 , however the waypoint bug persists.

**Comment by PiezPiedPy** [comment]
@dlrk2 Well that's a bummer, works fine for me on v1.4.1
Thanks for the info anyway, I have made a backport branch for 1.3.1 but unfortunately I am unable to test it with 1.3.1 due to low disk space 😞  Hopefully @fat-lobyte can test it.

By the way did you test with a waypoint from the KSP stock contracts, also did you do a clean install of Trajectories ?

**Comment by dlrk2** [comment]
I tried it with a manual waypoint, and the KSC button. I tried it with a clean Trajectories install. Thanks for the backport.

**Comment by dlrk2** [comment]
Once the backport branch has a compiled copy, I can test it. Maybe it just needs to be compiled with the earlier Unity?

**Comment by PiezPiedPy** [comment]
The backport has to be compiled with the KSP v1.3.1 Unity references, which means installing KSP 1.3.1 or the version of Unity used by 1.3.1, either way I don't have the space yet.
I will be getting a new SSD soon (few weeks) so will be able to build and test 😉

**Comment by PiezPiedPy** [comment]
@dlrk2 I uninstalled a couple of games and made some space, just compiled a release for 1.3.1
Hope it works for you, working fine on my system 😃 
[Trajectories_KSP1.3.1-v2.1.0.zip](https://github.com/neuoy/KSPTrajectories/files/1844677/Trajectories_KSP1.3.1-v2.1.0.zip)

**Comment by dlrk2** [comment]
Thanks for the recompile, it works fine, except the waypoint bug remains present. Is it possible the wrong version was compiled?

**Comment by PiezPiedPy** [comment]
@dlrk2 How far off is the Target, is it still 180 degrees ?

**Comment by dlrk2** [comment]
@PiezPiedPy I'll double check, but it looked identical as before, the value just decreases continuously. I'll try it with a waypoint from KSP (as opposed to the KSC button or a manual waypoint, which in both versions is placed properly, but drifts in longitude until below 100km)

**Comment by dlrk2** [comment]
Okay, the waypoint targeting works fine now. The other issue (#140 ) still persists

**Comment by PiezPiedPy** [comment]
@dlrk2 Thanks for letting me know, I was starting to pull my hair out wondering WTF is going on lol. :neckbeard:

Don't think there is anything we can do about #140 seems to be a KSP thing 😠
